export const predlozi = [
  { text: [`od`, `do`], padez: `g` },
  { text: [`iz`, `s(a)`], padez: `g` },
  { text: [`ispred`, `za`], padez: `g` },
  { text: [`izvan`, `van`], padez: `g` },
  { text: [`unutar`, `iznad`], padez: `g` },
  { text: [`ispod`, `više`], padez: `g` },
  { text: [`poviše`, `niže`], padez: `g` },
  { text: [`prije`, `uoči`], padez: `g` },
  { text: [`poslije`, `nakon`], padez: `g` },
  { text: [`za`, `tijekom`, `tokom`], padez: `g` },
  { text: [`dno`, `podno`, `nadno`, `odno`], padez: `g` },
  { text: [`vrh`, `povrh`, `navrh`, `uvrh`, `zavrh`], padez: `g` },
  { text: [`čelo`], padez: `g` },
  { text: [`nakraj`, `onkraj`, `krajem`, `potkraj`], padez: `g` },
  { text: [`sred`, `nasred`, `posred`, `usred`], padez: `g` },
  { text: [`oko`, `okolo`], padez: `g` },
  { text: [`blizu`, `kod`], padez: `g` },
  { text: [`kraj`, `pokraj`], padez: `g` },
  { text: [`pored`, `nadomok`, `nadohvat`], padez: `g` },
  { text: [`i`, `u`], padez: `g` },
  { text: [`mimo`], padez: `g` },
  { text: [`duž`, `uzduž`], padez: `g` },
  { text: [`širom`, `diljem`], padez: `g` },
  { text: [`preko`], padez: `g` },
  { text: [`bez`, `osim`], padez: `g` },
  { text: [`mjesto`, `umjesto`, `namjesto`], padez: `g` },
  { text: [`uime`, `putem`], padez: `g` },
  { text: [`(s) pomoću`, `posredstvom`], padez: `g` },
  { text: [`između`, `(na)spram`], padez: `g` },
  { text: [`put`, `protiv`, `nasuprot`, `usuprot`, `usprkos`], padez: `g` },
  { text: [`unatoč`, `zbog`], padez: `g` },
  { text: [`radi`, `zaradi`, `poradi`], padez: `g` },
  { text: [`glede`], padez: `g` },
  { text: [`prigodom`, `prilikom`, `povodom`], padez: `g` },
  { text: [`k(a)`], padez: `d` },
  { text: [`prema`], padez: `d` },
  { text: [`naprama`, `nadomak`, `nadohvat`, `nasuprot`, `usuprot`, `usprkos`], padez: `d` },
  { text: [`unatoč`, `protiv`], padez: `d` },
  { text: [`kroz`], padez: `a` },
  { text: [`niz`], padez: `a` },
  { text: [`uz`], padez: `a` },
  { text: [`po`], padez: `a` },
  { text: [`o`], padez: `a` },
  { text: [`na`], padez: `a` },
  { text: [`u`], padez: `a` },
  { text: [`mimo`], padez: `a` },
  { text: [`među`], padez: `a` },
  { text: [`nad`, `pod`], padez: `a` },
  { text: [`pred`, `za`], padez: `a` },
  { text: [`na`], padez: `l` },
  { text: [`o`], padez: `l` },
  { text: [`po`], padez: `l` },
  { text: [`prema`], padez: `l` },
  { text: [`pri`], padez: `l` },
  { text: [`u`], padez: `l` },
  { text: [`s(a)`], padez: `i` },
  { text: [`pred`], padez: `i` },
  { text: [`za`], padez: `i` },
  { text: [`nad(a)`, `pod(a)`], padez: `i` },
  { text: [`među`], padez: `i` },
] as const satisfies { text: string[]; padez: `v` | `n` | `a` | `g` | `i` | `d` | `l` }[];
